### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by robertmeta** [documentcloud/pdfshaver#4]
I am certain I am just missing it -- but I can't seem to find the license for this?

**Comment by robertmeta** [comment]
It seems like a ton of documentcloud projects contain no license files -- is there some global license documented somewhere?

**Comment by knowtheory** [comment]
Hey @robertmeta it's MIT licensed which is noted in the Gemspec, but i should probably stick the actual MIT notice in the repo.

**Comment by knowtheory** [comment]
Here you go: 9a5a46d
