### ISSUE TITLE
gem install pdfshaver fails on ubuntu

### ISSUE THREAD

**Issue by mikejmets** [documentcloud/pdfshaver#5]
When trying to install pdfshaver on ubunti 14.04, it failed and created this output http://pastie.org/10123749. First I must say I'm a python developer and know nothing about ruby. In trying to debug this I ventured into rake, I cloned pdfshaver from git, installed ruby-dev (and ruby-all-dev and ruby1.9.1-dev), rake-compiler, and bundler but end up with rake aborted (http://pastie.org/10123756)

**Comment by knowtheory** [comment]
Hey @mikejmets... I'm going to tell you the unsatisfying thing first.  We primarily tested with Ruby >=2 (and i should probably have specified that in the gemspec).

The installation instructions should work w/o a hitch for those purposes.  If you wanna get up and running directly w/o further input from us... getting a more recent ruby is probably a good way to go.  We're installing a recent ruby (2.2.x) using https://github.com/postmodern/ruby-install (and using chruby to set which ruby is available).  I forget which rubys ubuntu has access to out of the box but ruby2 should be available, or you could use ruby-install, rvm or rbenv (or just roll by hand).

We'll have to see what is up with ruby 1.9's compilation, i'm not sure when/what changes happened between 1.9.x and 2.x regarding the C/C++ interface for Ruby.

**Comment by mikejmets** [comment]
Thanks @knowtheory , I installed ruby2.1 and ruby2.1-dev and it installed first time. Does this mean that any other ruby gem the uses pdfshaver (like docsplit in my case) must be 2.1 as well?

**Comment by knowtheory** [comment]
Yep, 1.9 is obsolete at this point and as general advice i'd recommend staying up on 2.x.

**Comment by mikejmets** [comment]
Thanks.
