### ISSUE TITLE
Benchmarks vs docsplit?

### ISSUE THREAD

**Issue by cdunn** [documentcloud/pdfshaver#6]
Thanks for putting this gem together.  Been testing PDFium and wondering if you guys already came to a conclusion on the performance tradeoff between it and the methods in Docsplit (poppler/etc) for image extraction?

Just wondering before diving in and repeating work.

**Comment by knowtheory** [comment]
Hey @cdunn, we did do some very rudimentary testing prior to putting this into production (and in fact we use a modified prerelease branch of docsplit to do so right now).  From everything we've seen, using pdfium to render images is about a factor of 10 faster than using graphicsmagick + ghostscript.

We totally should put together a benchmark suite though.
